name: Publish sub‑packages to npm

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    # одну и ту же задачу будем выполнять для каждого пакета
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - Gameplay.PlayableNodes.Core
          - Gameplay.PlayableNodes.Tween

    # все run‑скрипты в рамках цикла будут выполняться внутри конкретной папки‑пакета
    defaults:
      run:
        working-directory: ${{ matrix.package }}

    steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
   #Install Node.js, with the version 12 and using the registry URL of npm, this could be changed to a custom registry or the GitHub registry.
     - uses: actions/setup-node@v1
         with:
         node-version: 12
         registry-url: https://registry.npmjs.com/
  
     # Command to install the package dependencies
     - run: yarn install

      # 4. Публикуем текущий пакет
      - name: Publish ${{ matrix.package }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
